Add readme and update description
mirumee/macaw-ui pull request #25
Opened 2021-07-07 14:26 UTC by dominik-zeglen

2021-07-08 07:44 UTC, kamilpastuszka requested changes

2021-07-08 07:44 UTC, kamilpastuszka commented on README.md
> +You can find most of the elements used in the creation of Saleor’s dashboard interface and use it to create projects for your specific purposes. Take a look a our [storybook docs](macaw-ui.vercel.app
storybook docs link doesn't work

2021-07-08 07:45 UTC, dominik-zeglen commented on README.md
> +You can find most of the elements used in the creation of Saleor’s dashboard interface and use it to create projects for your specific purposes. Take a look a our [storybook docs](macaw-ui.vercel.app
Oh nice catch

2021-07-08 09:20 UTC, orzechdev approved these changes

2021-07-08 10:51 UTC, kamilpastuszka approved these changes

2021-07-08 13:55 UTC, karolkielecki requested changes

2021-07-08 13:55 UTC, karolkielecki commented on README.md
> +You can find most of the elements used in the creation of Saleor’s dashboard interface and use it to create projects for your specific purposes. Take a look a our [storybook docs](macaw-ui.vercel.app
```suggestion
You can find most of the elements used in the creation of Saleor's dashboard interface and use it to create projects for your specific purposes. Take a look at our [storybook docs](macaw-ui.vercel.app). You can find guides, component overview, and project ideas there.
```

2021-07-08 13:55 UTC, karolkielecki commented on README.md
> +Have a great time working on your projects and empowering your users.
```suggestion
Have a great time working on your projects and empowering your users. If you have any questions, feel free to let us know on [GitHub Discussions](https://github.com/mirumee/saleor/discussions). 
```

2021-07-08 13:55 UTC, karolkielecki commented on README.md
> +This is an official React UI Kit for Saleor, a GraphQL-First e-commerce platform for perfectionists.
```suggestion
This is the official React UI Kit for Saleor—an open-source GraphQL-first and Next.js ready e-commerce platform.
```

2021-07-12 10:39 UTC, karolkielecki approved these changes

2021-07-12 11:20 UTC, merged