Add tooltips to savebar buttons
mirumee/macaw-ui pull request #40
Opened 2021-07-29 10:06 UTC by orzechdev

Needed for fulfillment page https://app.clickup.com/t/2549495/SALEOR-3860

In dashboard: https://github.com/mirumee/saleor-dashboard/pull/1248

2021-07-29 11:34 UTC, dominik-zeglen requested changes

2021-07-29 11:34 UTC, dominik-zeglen commented on src/theme/createSaleorTheme/createSaleorTheme.ts
> +          fontSize: "0.8em",
```suggestion
          fontSize: theme.typography.caption.fontSize,
```

2021-07-29 11:43 UTC, dominik-zeglen approved these changes

2021-07-30 08:16 UTC, mmarkusik approved these changes

2021-07-30 11:41 UTC, merged